[package]
name = "ltime"
version = "0.1.0"
authors = ["Taiki Sugawara <buzz.taiki@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
regex = "1.7.0"
